# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :deploy do
    ensure_git_status_clean
    run_tests
    old_build_number = get_build_number
    new_build_number = increment_build_number
    sh("sed", "-i", "", "s/(#{old_build_number})/(#{new_build_number})/g", "../manifest.plist")
    git_add(path: "manifest.plist")
    commit_version_bump
    push_to_git_remote
    gym(output_directory: "s3", output_name: "National Champions.ipa")
  end
end
